export const SHOP_DATA = {
  data: [
    {
      name: "Brown Brim",
      description: "",
      imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
      price: 25,
      inStock: 3,
    },
    {
      name: "Blue Beanie",
      description: "",
      imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
      price: 18,
      inStock: 3,
    },
    {
      name: "Brown Cowboy",
      description: "",
      imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
      price: 35,
      inStock: 3,
    },
    {
      name: "Grey Brim",
      description: "",
      imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
      price: 25,
      inStock: 3,
    },
    {
      name: "Green Beanie",
      description: "",
      imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
      price: 18,
      inStock: 3,
    },
    {
      name: "Palm Tree Cap",
      description: "",
      imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
      price: 14,
      inStock: 3,
    },
    {
      name: "Red Beanie",
      description: "",
      imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
      price: 18,
      inStock: 3,
    },
    {
      name: "Wolf Cap",
      description: "",
      imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
      price: 14,
      inStock: 3,
    },
    {
      name: "Blue Snapback",
      description: "",
      imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
      price: 16,
      inStock: 3,
    },
    {
      name: "Adidas NMD",
      description: "",
      imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
      price: 220,
      inStock: 3,
    },
    {
      name: "Adidas Yeezy",
      description: "",
      imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
      price: 280,
      inStock: 3,
    },
    {
      name: "Black Converse",
      description: "",
      imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
      price: 110,
      inStock: 3,
    },
    {
      name: "Nike White AirForce",
      description: "",
      imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
      price: 160,
      inStock: 3,
    },
    {
      name: "Nike Red High Tops",
      description: "",
      imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
      price: 160,
      inStock: 3,
    },
    {
      name: "Nike Brown High Tops",
      description: "",
      imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
      price: 160,
      inStock: 3,
    },
    {
      name: "Air Jordan Limited",
      description: "",
      imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
      price: 190,
      inStock: 3,
    },
    {
      name: "Timberlands",
      description: "",
      imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
      price: 200,
      inStock: 3,
    },
    {
      name: "Black Jean Shearling",
      description: "",
      imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
      price: 125,
      inStock: 3,
    },
    {
      name: "Blue Jean Jacket",
      description: "",
      imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
      price: 90,
      inStock: 3,
    },
    {
      name: "Grey Jean Jacket",
      description: "",
      imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
      price: 90,
      inStock: 3,
    },
    {
      name: "Brown Shearling",
      description: "",
      imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
      price: 165,
      inStock: 3,
    },
    {
      name: "Tan Trench",
      description: "",
      imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
      price: 185,
      inStock: 3,
    },
    {
      name: "Blue Tanktop",
      description: "",
      imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
      price: 25,
      inStock: 3,
    },
    {
      name: "Floral Blouse",
      description: "",
      imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
      price: 20,
      inStock: 3,
    },
    {
      name: "Floral Dress",
      description: "",
      imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
      price: 80,
      inStock: 3,
    },
    {
      name: "Red Dots Dress",
      description: "",
      imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
      price: 80,
      inStock: 3,
    },
    {
      name: "Striped Sweater",
      description: "",
      imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
      price: 45,
      inStock: 3,
    },
    {
      name: "Yellow Track Suit",
      description: "",
      imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
      price: 135,
      inStock: 3,
    },
    {
      name: "White Blouse",
      description: "",
      imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
      price: 20,
      inStock: 3,
    },
    {
      name: "Camo Down Vest",
      description: "",
      imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
      price: 325,
      inStock: 3,
    },
    {
      name: "Floral T-shirt",
      description: "",
      imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
      price: 20,
      inStock: 3,
    },
    {
      name: "Black & White Longsleeve",
      description: "",
      imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
      price: 25,
      inStock: 3,
    },
    {
      name: "Pink T-shirt",
      description: "",
      imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
      price: 25,
      inStock: 3,
    },
    {
      name: "Jean Long Sleeve",
      description: "",
      imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
      price: 40,
      inStock: 3,
    },
    {
      name: "Burgundy T-shirt",
      description: "",
      imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
      price: 25,
      inStock: 3,
    },
  ],
};
